# Generated by Django 4.2.9 on 2024-02-22 17:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('category_slug', models.SlugField(max_length=250, unique=True, verbose_name='Слаг')),
                ('category_content', models.TextField(blank=True, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customers_name', models.CharField(db_index=True, max_length=100, verbose_name='Категория клиента')),
                ('customers_slug', models.SlugField(max_length=250, unique=True, verbose_name='Слаг')),
                ('customers_content', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория клиента',
                'verbose_name_plural': 'Категории клиентов',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_title', models.CharField(max_length=200, verbose_name='Название акции')),
                ('slug', models.SlugField(max_length=250, unique=True, validators=[django.core.validators.MinLengthValidator(5, message='Минимум 5 символов'), django.core.validators.MaxLengthValidator(250, message='Максимум 250 символов')], verbose_name='Slug')),
                ('stock_content', models.TextField(blank=True, verbose_name='Описание акции')),
                ('old_price', models.IntegerField(blank=True, null=True, verbose_name='Старая цена')),
                ('new_price', models.IntegerField(blank=True, null=True, verbose_name='Цена по акции')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('not_published', models.BooleanField(default=False, verbose_name='Снять с публикации')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Загрузите фото')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала акции')),
                ('stop_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания акции')),
                ('for_man', models.BooleanField(default=False, verbose_name='Для мужчин')),
                ('for_woman', models.BooleanField(default=False, verbose_name='Для женщин')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=250, unique=True, validators=[django.core.validators.MinLengthValidator(5, message='Минимум 5 символов'), django.core.validators.MaxLengthValidator(250, message='Максимум 250 символов')], verbose_name='Slug')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('is_price', models.IntegerField(null=True, verbose_name='Цена')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('not_published', models.BooleanField(default=False, verbose_name='Снять с публикации')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Загрузите фото')),
                ('for_man', models.BooleanField(default=False, verbose_name='Для мужчин')),
                ('for_woman', models.BooleanField(default=False, verbose_name='Для женщин')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Category', to='price_list.category', verbose_name='Категории')),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Customers', to='price_list.customers', verbose_name='Категория клиента')),
            ],
            options={
                'verbose_name': 'Прайс',
                'verbose_name_plural': 'Прайс',
            },
        ),
    ]
