# Generated by Django 4.2.9 on 2024-02-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='not_published',
            field=models.BooleanField(default=False, verbose_name='Снять с публикации'),
        ),
    ]
