# Generated by Django 4.2.9 on 2024-02-22 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='for_man',
        ),
        migrations.RemoveField(
            model_name='price',
            name='for_woman',
        ),
    ]
