# Generated by Django 4.2.9 on 2024-02-24 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='is_customers',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='price_list.customers', verbose_name='Категория клиента'),
        ),
    ]
