# Generated by Django 4.2.9 on 2024-02-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Заголовок'),
        ),
    ]
