# Generated by Django 4.2.9 on 2024-02-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_list', '0002_price_not_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
