# Generated by Django 4.2.9 on 2024-02-22 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_list', '0002_remove_price_for_man_remove_price_for_woman'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='customers',
        ),
    ]
