# Generated by Django 4.2.9 on 2024-02-15 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_list', '0003_alter_price_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, validators=[django.core.validators.MinLengthValidator(5, message='Минимум 5 символов'), django.core.validators.MaxLengthValidator(100, message='Максимум 100 символов')], verbose_name='Slug'),
        ),
    ]
