# Generated by Django 4.2.9 on 2024-02-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_list', '0003_price_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Загрузите фото'),
        ),
    ]
